# DATA LOADER SETTINGS
dataloading:
  path_to_data: "data/raw/P01"

# PREPROCESSING SETTINGS
preprocessing:
  condition: "MathxHard"
  partition_size: 250
  fixed_size: 10990

# ARCHITECTURE SETTINGS
architecture:
  latent_dims: 2

# FITTING SETTINGS
fitting:
  epochs: 32
  batch_size: 1
