# DATA LOADER SETTINGS
dataloading:
  path_to_data: "data/raw/P01"

# PREPROCESSING SETTINGS
preprocessing:
  condition: "MathxHard"
  rolling_window_size: 250
  fixed_size: 10990

# MODELLING SETTINGS
# TBD